
package se.kth.webservice.second.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Authentication", targetNamespace = "http://service.second.webservice.kth.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Authentication {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.LoginResponse")
    @Action(input = "http://service.second.webservice.kth.se/Authentication/loginRequest", output = "http://service.second.webservice.kth.se/Authentication/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns se.kth.webservice.second.service.TestingHeadersResponse
     */
    @WebMethod
    @WebResult(name = "testingHeadersResponse", targetNamespace = "http://service.second.webservice.kth.se/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://service.second.webservice.kth.se/Authentication/testingHeadersRequest", output = "http://service.second.webservice.kth.se/Authentication/testingHeadersResponse")
    public TestingHeadersResponse testingHeaders(
        @WebParam(name = "testingHeaders", targetNamespace = "http://service.second.webservice.kth.se/", partName = "parameters")
        TestingHeaders parameters,
        @WebParam(name = "token", targetNamespace = "http://service.second.webservice.kth.se/", header = true, partName = "token")
        String token);

}
