
package se.kth.webservice.second.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookTicket", targetNamespace = "http://service.second.webservice.kth.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookTicket {


    /**
     * 
     * @param arg0
     * @return
     *     returns se.kth.webservice.second.service.Availability
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.CheckAvailabilityResponse")
    @Action(input = "http://service.second.webservice.kth.se/BookTicket/checkAvailabilityRequest", output = "http://service.second.webservice.kth.se/BookTicket/checkAvailabilityResponse")
    public Availability checkAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns se.kth.webservice.second.service.Booking
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTicket", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.BookTicket_Type")
    @ResponseWrapper(localName = "bookTicketResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.BookTicketResponse")
    @Action(input = "http://service.second.webservice.kth.se/BookTicket/bookTicketRequest", output = "http://service.second.webservice.kth.se/BookTicket/bookTicketResponse")
    public Booking bookTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
