
package se.kth.webservice.second.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IssueTicket", targetNamespace = "http://service.second.webservice.kth.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IssueTicket {


    /**
     * 
     * @param arg0
     * @return
     *     returns se.kth.webservice.second.service.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "issueTicket", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.IssueTicket_Type")
    @ResponseWrapper(localName = "issueTicketResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.IssueTicketResponse")
    @Action(input = "http://service.second.webservice.kth.se/IssueTicket/issueTicketRequest", output = "http://service.second.webservice.kth.se/IssueTicket/issueTicketResponse")
    public Ticket issueTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
