
package se.kth.webservice.second.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IssueTicketService", targetNamespace = "http://service.second.webservice.kth.se/", wsdlLocation = "http://localhost:9091/tickets?wsdl")
public class IssueTicketService
    extends Service
{

    private final static URL ISSUETICKETSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISSUETICKETSERVICE_EXCEPTION;
    private final static QName ISSUETICKETSERVICE_QNAME = new QName("http://service.second.webservice.kth.se/", "IssueTicketService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9091/tickets?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISSUETICKETSERVICE_WSDL_LOCATION = url;
        ISSUETICKETSERVICE_EXCEPTION = e;
    }

    public IssueTicketService() {
        super(__getWsdlLocation(), ISSUETICKETSERVICE_QNAME);
    }

    public IssueTicketService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISSUETICKETSERVICE_QNAME, features);
    }

    public IssueTicketService(URL wsdlLocation) {
        super(wsdlLocation, ISSUETICKETSERVICE_QNAME);
    }

    public IssueTicketService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISSUETICKETSERVICE_QNAME, features);
    }

    public IssueTicketService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IssueTicketService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IssueTicket
     */
    @WebEndpoint(name = "IssueTicketPort")
    public IssueTicket getIssueTicketPort() {
        return super.getPort(new QName("http://service.second.webservice.kth.se/", "IssueTicketPort"), IssueTicket.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IssueTicket
     */
    @WebEndpoint(name = "IssueTicketPort")
    public IssueTicket getIssueTicketPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.second.webservice.kth.se/", "IssueTicketPort"), IssueTicket.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISSUETICKETSERVICE_EXCEPTION!= null) {
            throw ISSUETICKETSERVICE_EXCEPTION;
        }
        return ISSUETICKETSERVICE_WSDL_LOCATION;
    }

}
