
package se.kth.webservice.second.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Itinerary", targetNamespace = "http://service.second.webservice.kth.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Itinerary {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<se.kth.webservice.second.service.TravelPath>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableItineraries", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAvailableItineraries")
    @ResponseWrapper(localName = "getAvailableItinerariesResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAvailableItinerariesResponse")
    @Action(input = "http://service.second.webservice.kth.se/Itinerary/getAvailableItinerariesRequest", output = "http://service.second.webservice.kth.se/Itinerary/getAvailableItinerariesResponse")
    public List<TravelPath> getAvailableItineraries(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns se.kth.webservice.second.service.Airport
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAirportById", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAirportById")
    @ResponseWrapper(localName = "getAirportByIdResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAirportByIdResponse")
    @Action(input = "http://service.second.webservice.kth.se/Itinerary/getAirportByIdRequest", output = "http://service.second.webservice.kth.se/Itinerary/getAirportByIdResponse")
    public Airport getAirportById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns se.kth.webservice.second.service.Airline
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAirlineById", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAirlineById")
    @ResponseWrapper(localName = "getAirlineByIdResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetAirlineByIdResponse")
    @Action(input = "http://service.second.webservice.kth.se/Itinerary/getAirlineByIdRequest", output = "http://service.second.webservice.kth.se/Itinerary/getAirlineByIdResponse")
    public Airline getAirlineById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<se.kth.webservice.second.service.Departure>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeparturesFromRoute", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetDeparturesFromRoute")
    @ResponseWrapper(localName = "getDeparturesFromRouteResponse", targetNamespace = "http://service.second.webservice.kth.se/", className = "se.kth.webservice.second.service.GetDeparturesFromRouteResponse")
    @Action(input = "http://service.second.webservice.kth.se/Itinerary/getDeparturesFromRouteRequest", output = "http://service.second.webservice.kth.se/Itinerary/getDeparturesFromRouteResponse")
    public List<Departure> getDeparturesFromRoute(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
